# Default values for trdl.

replicaCount: 1

ns: trdlns

image:
  repository: ghcr.io/anniemartina/myhttpserver/trdl

service:
  name: trdlsvc
  type: LoadBalancer
  port: 80

secret: 
  name: trdlsecret
  type: kubernetes.io/dockerconfigjson
