apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "trdl.labels" . | nindent 4 }}
  namespace: {{ .Values.ns }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trdl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trdl.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
          - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
        - name: {{ .Values.secret }}
