apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
     {{- include "trdl.labels" . | nindent 4 }}
  namespace: {{ .Values.ns }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "trdl.selectorLabels" . | nindent 4 }}

